org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# Minecraft Properties
minecraft_version=26.1
minecraft_version_range=[26.1,27.1)
neo_version=26.1.0.1-beta

# Mod Properties
mod_id=cratedelightcroptopia
mod_name=Crate Delight: Croptopia
mod_license=MIT
mod_version=26.06.24-26.1-neoforge
mod_authors=Axperty
mod_description=A mod that adds crates and bags for the Croptopia mod.
mod_group_id=com.axperty.cratedelightcroptopia