modLoader="javafml"
loaderVersion="[41,)"
license="${mod_license}"

[[mods]]
    modId="cratedelightcroptopia"
    version="24.12.28-1.19-forge"
    displayName="Crate Delight: Croptopia"
    authors="Axperty"
    description="A mod that adds crates and bags for the Croptopia mod."
    logoFile="assets/cratedelight/logo.png"

[[dependencies.cratedelightcroptopia]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.cratedelightcroptopia]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.cratedelightcroptopia]]
    modId="cratedelight"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.cratedelightcroptopia]]
    modId="croptopia"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
